# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 489a6ccb1aadcc6fa8c9f55d4e77643ade57045b36a2a5111b35945053c7727913f01b1b8a7d862892bbf1915a0cda011d3859c9df9fc9881f693949d84d9020

test:
  secret_key_base: 82141a62876771048f477955fe0170132f05795e16e3e94f01a5e6210c03354dfcd611ff31ef3295ab1a77d01ce059a4903750713d2055aa77190275c1166f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
